# Generated by Django 6.0.3 on 2026-03-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
