# Generated by Django 6.0.3 on 2026-03-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="quiz_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="quiz_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="video_watched",
            field=models.BooleanField(default=False),
        ),
    ]
