# Generated by Django 6.0.3 on 2026-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_userxp_streak_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("first_lesson", "First Lesson"),
                    ("five_lessons", "5 Lessons Completed"),
                    ("first_quiz", "First Quiz Passed"),
                    ("perfect_score", "Perfect Score"),
                    ("first_try_perfect", "Perfect on First Try"),
                    ("streak_3", "3 Day Streak"),
                ],
                max_length=30,
            ),
        ),
    ]
